### ISSUE TITLE
Got exception for bot3

### ISSUE THREAD

**Issue by qwertyui108** [shiftcodeYT/PokeBot3#102]
Any idea?
Thanks

 Exception: Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at PokemonGo.RocketAPI.GeneratedCode.Response.MergeFrom(CodedInputStream input) in C:\Users\simon\Documents\GitHub\PokeBot3\PokemonGo.RocketAPI\GeneratedCode\Response.cs:line 348
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot3\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot3\PokemonGo.RocketAPI\Client.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot3\PokemonGo.RocketAPI.Logic\Logic.cs:line 128

**Comment by shiftcodeYT** [comment]
Seems to be a server error. Does this happen often?

**Comment by shiftcodeYT** [comment]
Yup, servers are insanely unstable again. http://ispokemongodownornot.com

**Comment by qwertyui108** [comment]
i downloaded it today and never worked yet

**Comment by BukkitTNT** [comment]
The bot is in the moment unstable wait a few days, shiftcode is working on an update.
