### ISSUE TITLE
can use bot at lvl 4

### ISSUE THREAD

**Issue by scottrecor** [shiftcodeYT/PokeBot3#114]
do i have to pick a team before using this bot

**Comment by shiftcodeYT** [comment]
@scottrecor Nope, you can just run it.

**Comment by scottrecor** [comment]
i get invaldprotocolbufferexception: skiplastField called on end-group tag indicating that the  corresponding start-group was missing

**Comment by shiftcodeYT** [comment]
@scottrecor Seems like a server error.

**Comment by scottrecor** [comment]
server error for the bot or pokemon go i can log into the game just fine

**Comment by scottrecor** [comment]
exact error

Exception: Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at PokemonGo.RocketAPI.GeneratedCode.Response.MergeFrom(CodedInputStream input) in C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI\GeneratedCode\Response.cs:line 348
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI\Client.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI.Logic\Logic.cs:line 128

**Comment by shiftcodeYT** [comment]
@scottrecor Are you behind a firewall?

**Comment by scottrecor** [comment]
not that i am aware of is there certain ports that need to be open if so

**Comment by WhiteShadow7** [comment]
I Have the same Error on my Azure virtual Machine :/.  Does the app need some special permission?

**Comment by shiftcodeYT** [comment]
Azure seems to be not working. Can you try on your home PC? I'm not using azure, but it's working on a Windows VPS @ Hosting90.eu for me.

**Comment by shiftcodeYT** [comment]
Azure was IPblocked by niantic. Same for other hosting companies.

**Comment by scottrecor** [comment]
So proxy time
