### ISSUE TITLE
Walk Speed set to 0 gives error.

### ISSUE THREAD

**Issue by tiny1980** [shiftcodeYT/PokeBot3#134]
Just ran current version to look up some IVs quickly on the pokemon list, and didn't want to aimlessly walk around back to "default location' since there are no pokestops.

I set the Speed to 0 km/h, and I get the following error.  It's not a huge deal, as I can't see many people setting walk speed to '0', although, I just wanted to point it out.  Judging by the error message, a '0' value should work.  The error however has to do with time it seems.  The bot can't calculate 'Infinite Seconds as it current;y is.

`[13:42:25]
[13:42:25] PokemonGO Server Status:
[13:42:25] Online since ~15h.
[13:42:25] Server anwsers in ~2.32 seconds.
[13:42:25] Pokemon Trainer Club Server Status:
[13:42:25] Online since ~19h.
[13:42:25] Server anwsers in ~1.49 seconds.
[13:42:25] _____________________________
[13:42:25] We cant find any PokeStops in a range of 5000m!
[13:42:26] We cant find any PokeStops, which are unused! Probably Server unstabl
e, or you visted them all. Retrying..
[13:42:26] Walking back to Default Location.
[13:42:26] Distance to target location: 0 meters. Will take Infinity seconds!
[13:42:27] Exception: System.ArgumentOutOfRangeException: The value needs to be
either -1 (signifying an infinite timeout), 0 or a positive integer.
Parameter name: millisecondsDelay
   at System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay, CancellationTok
en cancellationToken)
   at System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay)
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in
C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI.Logic\Navigatio
n.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.
MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI.L
ogic\Logic.cs:line 440
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI.Logic\Logic.cs:line
 139
[13:42:27] Starting again.. But waiting 10 Seconds..
`

**Comment by FallenDev** [comment]
As of right now we have no idea if this problem will extend to our new version. If it does, please repost this then.
